### ISSUE TITLE
throughput / volume metrics

### ISSUE THREAD

**Issue by mwielbut** [enobufs/dtimer#13]
Hey, dtimer look like it's exactly what we need! Just wondering if you've been able to run any performance tests on it? Are there any known issues with scaling up to millions of stored timer events, and processing 1000's of timer events a second? Assuming we have a large enough Redis instance and several "listeners"...

**Comment by enobufs** [comment]
Hi @mwielbut.  My usage of this module did not require very many (frequent) events.  I would assume the bottle neck would be the CPU usage on redis where production of events is assumed to be much less than consumption of those, of course. That said, I do not have any performance metrics on a high load scenario, unfortunately.

Keeping the usage reasonability low would allow you to switch to SQS (if on AWS), too. For high frequency async event handling, you may want to consider a worker solution, too.

**Comment by mwielbut** [comment]
Thanks! I'll let you know what I discover.
